spring.application.name=lotte_cmc_tech_test

# mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB_NAME}?createDatabaseIfNotExist=true
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# jwt
app.auth.token.secretKey=${JWT_AT_SCK}
app.auth.token.expInMilSec=${JWT_AT_EXP}
app.auth.refreshToken.secretKey=${JWT_RT_SCK}
app.auth.token.refreshInMilSec=${JWT_RT_EXP}

logging.level.org.springframework.security=DEBUG